### ISSUE TITLE
Dataset - Nearshore Macrophyte  Stable Isotopes - BC Central Coast - 2014-2019

### ISSUE THREAD

**Issue by hakai-it** [HakaiInstitute/metadata-review#57] opened 2023-06-08 15:50 UTC
## Nearshore Macrophyte  Stable Isotopes - BC Central Coast - 2014-2019

https://cioos-siooc.github.io/metadata-entry-form/#/en/hakai/Q7WjoEJM1Sc9HrFLJCRgKAtMzTH2/-MvdswVi63ta0CliHbKN

### In General

- [x] No previous versions of this metadata record exist (eg for earlier versions of the data, if so update that record rather than creating a new one)

#### Dataset title:

- [x] No version information in the title
- [x] Frontloaded (with the most important information first)
- [x] Include the geographical region the data apply to
- [x] Short – aim for 60 characters including spaces
- [x] Does not include acronyms – put these in the keywords
- [x] Does not include the word “dataset”
- [ ] Time series datasets should include “time series” at the end of the title
- [x] Does not include the time period (this is covered in the temporal extents fields)

#### Abstract

- [x] Abbreviations have been expanded upon at first mention

### Spatial

- [ ] Ensure that Depth or Height Positive is correctly selected

### Contact

- [ ] ROR and ORCID(s) are included and linked properly where applicable
- [ ] For datasets where DFO is a partner, ensure 'parent' ROR is added (https://ror.org/02qa1x782). DFO 'child' organizations (i.e. CHS) and their ROR are optional.
- [x] The citation in the metadata record matches the preferred citation mentioned in the data package.
- [x] Include Hakai Institute as Publisher (& Distributor?)
- [x] Make sure email address is provided if the role is 'Point of Contact'
- [x] Add contact affiliation where known

### Resources

- [x] Resource links go to specific dataset download (not generic platform like waterproperties.ca)
- [x] Readme, changelog, data dictionary, protocols included in data-package
- [ ] An archive folder for older data versions is included in the data package if the version is _not_ 1.0
- [x] Links work
- [ ] Resource link links to a download of the compressed data package (.zip) of the correct version.
- [ ] All files in the data package can be opened and are not corrupt

**Comment by Br-Johnson** [comment] 2023-06-09 21:21
@Tyr30 

Hey Tyrel. It looks like a previous version of this dataset already exists at https://doi.org/10.21966/q31x-qg72

For a primer on how we're suggesting we deal with new versions of data please see our documentation here: https://data.hakai.org/data-provider-documentation/dataset-versioning

In this case I would suggest editing the original metadata record and discarding this newly submitted one. Be sure to change the title to remove any reference to the time range, and add a sub-folder to your google drive folder for older versions of the data.

Also please have a look through this checklist to make sure your original record conforms to these recommendations. 

Let me know if you have any questions or want to schedule a quick call to discuss the best way forward here.

**Comment by Tyr30** [comment] 2023-06-13 21:04
Hey Brett, sorry about that. I think I made this record before realizing that the original one was already ported from the old catalogue. Submitted it the other day without thinking.

**Comment by Br-Johnson** [comment] 2023-06-14 16:35
OK no problem Tyrel! Happy to help, especially since this process has changed quite a few times.

How would you like to proceed? Do my suggestions above make sense?

**Comment by Tyr30** [comment] 2023-06-20 17:57
Ok, thanks for the info. How would I edit the existing entry? I never made an intake form for that one, pretty sure it was copied over directly.

**Comment by Br-Johnson** [comment] 2023-06-21 17:14
Hey @Tyr30 OK gotcha. In that case, go to: https://cioos-siooc.github.io/metadata-entry-form/#/en/hakai/submissions

Sign in with your hakai gmail. 

Click on the 'Review submission' link on the left hand menu.

Find 'Nearshore Macrophyte Stable Isotopes - BC Central Coast - 2014-2018'

Click the View button on the right hand side (eye icon) and then go through and edit the record as needed.

When you've done that leave me a message here and I can have a look through to make sure it's all good or answer any questions you have.
Cheers,
Brett

**Comment by Tyr30** [comment] 2023-06-28 19:46
Ok @Br-Johnson, I've gone through and made edits to this dataset

**Comment by Tyr30** [comment] 2023-06-28 20:32
I'm also in the process of updating the metadata for a bunch of other datasets

**Comment by Br-Johnson** [comment] 2023-06-29 17:14
Sounds good @Tyr30 I'm just going through the review checklist and reviewing https://catalogue.hakai.org/dataset/ca-cioos_288ea4b2-3706-4256-8146-02bd0265585b and noticed a few minor things

* Consider adding 'Time Series' to the title if this is intended to be a long-term dataset going beyond ~ 5 years
* Consider adding some limitations affecting the dataset. For example, what biases may exist in the data or what traps might one fall into when interpreting and re-using the data?
* I noticed the vertical extent of the dataset in meters uses the "Height Positive" type of measurement. That means the data are from above to surface of the water. I assume that's correct because these were collected in the intertidal zone?
* There's a few updates to authors you'll need to make. Keep in mind you can hit the save button next to each persons name to save all these details for future records as well
* You and your collaborators to sign up for an ORCID: https://orcid.org/register and include those ORCIDs in the Contact section for each co-author. This is important for gaining credit for datasets published.
* Similarly, you'll need to include the Hakai ROR ID for each co-author. Just start typing Hakai in the ROR search field and you'll see Hakai Institute pop up as an option. 
* You may want to include an archived version (v1.0.0) since there's been an update to v1.0.1 for reproducibility. If so you can upload that to the Google Drive storage location or send it to me if you don't have permissions

Thanks for going through all this Tyrel!

**Comment by Br-Johnson** [comment] 2023-11-14 23:51
Hey @Tyr30 just wondering if you could comment on some of the changes I proposed. Otherwise I will close this issue

**Comment by Tyr30** [comment] 2024-01-08 18:40
Hi @Br-Johnson, sorry for the delay on this. I can go through your points.

1. The dataset hasn't been updated for a long time. Theoretically, if we collect isotopes in the future they will be added to this package.
2. I like the idea of saying something about limitations, in principle. Where were you thinking we would add this info? Into the readme?
3. Hmm, a lot of this dataset was collected in the subtidal. It might make more sense to change it to height negative?
4. I can update the authorship for sure
5. I've added ORC ids for authors who have them. I can bring it up to those that don't.
6. Ok, I didn't know this was a thing. I can add that for sure
7. I can upload version 1.0, yes

Thanks Brett!

**Comment by Br-Johnson** [comment] 2024-01-15 18:58
Hey @Tyr30 

Limitations to interpretation can go in the Readme file if they are quite long. If it's a short few sentences, that could go in the metadata intake form at the very bottom of the 'Dataset Identification' tab.

If the work was done under the surface of the water, ie subtidal, it should be depth positive.

Thanks for making all those other changes! Could you let me know on here once you've more or less wrapped that all up and so I can close out this issue?

Cheers!

**Comment by timvdstap** [comment] 2024-12-04 17:26
I believe conversations on this record are being continued in #92

**Closed by timvdstap** 2024-12-04 17:26 UTC
